name: "Build using Build8"

on:
  - push

jobs:
  build8:
    uses: 8x8/build8/.github/workflows/cloud8_app.yml@v1.1.0
    with:
      version: "1.0"
      java_version: "${{ steps.parse_java.outputs.group1 }}"
      maven_version: "${{ steps.parse_maven.outputs.group1 }}"
      helm_chart:  "${{ steps.parse_helm_path.outputs.group1 }}"
