# Important! First set the MFE CI and MFE CD (non-prod) workflows. Just after you're done with CI/CD (non-prod) start with CD (prod).
name: MFE CD Prod

# Workflow trigger setup. For more information: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Workflow is exectued when it is triggered manually
  # More info at: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      environment:
        description: 'Production environment'
        type: environment
      ignoreEnvironments:
        description: 'Release to ALL production'
        type: boolean
      package:
        description: Complete package name (name@build)
        type: string
  
  # Workflow is run on a scheduled time. Configuration works with specific UTC times using POSIX cron syntax.
  # More info at: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # Remove the following config if you don't need scheduled production released
  # Example: runs at 10:00 AM (UTC) on each Tue, Wed, Thu.
  schedule:
    - cron:  '0 10 * * 2,3,4'

jobs:
  cd:
    name: cd
    uses: 8x8/platform-ui-mfe-cd-prod-workflow/.github/workflows/mfe-cd-prod.yml@v3.2
    with:
      # Relative path to workspace directory. 
      # Root directory by default. 
      # Remove if your project is not a monorepo with multiple packages inside
      # Use the same value as for MFE CI!
      # Exmple: packages
      workspaceDirectory:

      # Flag that is used to decide whether to create an RP ticket for this deployment.
      # Also, this will send a message to the Release Today Work room
      # for each Production environment for which the deployment was finished.
      # Is set to false by default.
      createRpTicket:

      # Release notes for the RP ticket (if the flag for the ticket is set to true).
      # If omitted, an automated message will be created.
      releaseNotes:

      # The rollback plan for the RP ticket (if the flag for the ticket is set to true).
      # Run previous pipeline will be used by default.
      rollbackPlan:
      
    # For more information and detailed docs please check 8x8/platform-ui-mfe-cd-prod-workflow
    secrets: inherit

