name: MFE CI

# Workflow trigger setup. For more information: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Runs your workflow when you push a commit or tag.
  push:
    # Running your workflow only when a push to specific branches occurs
    branches:
      - $default-branch
      - releases/**
      - feature/**
  # Runs your workflow when activity on a pull request in the workflow's repository occurs.
  pull_request:
    branches:
      - '*'
  # Trigger workflow manually
  workflow_dispatch:

jobs:
  ci:
    name: ci
    # For more information and detailed docs please check 8x8/platform-ui-mfe-ci-workflow
    # Info: to increase readability of your workflow and support the future default value updates, please delete the keys you're not using
    uses: 8x8/platform-ui-mfe-ci-workflow/.github/workflows/mfe-ci.yml@v3.2.2
    with:
      # Node version used to run the CI process. Allows values specfied for actions/setup-node@v3 (node-version)
      # Default: '18'
      nodeVersion:

      # Package manager used in the project
      # Default: npm
      packageManager:
      
      # Install command
      # Default: npm ci
      # Example: yarn install
      install:

      # Test command
      # Example: yarn test
      test: 

      # Lint command
      # Example: yarn lint
      lint: 

      # Boolean flag to run sonar-scanner
      # Example: true/false
      sonar: 

      # Additional optional arguments to the sonar-scanner
      # Example: >
      # -Dsonar.projectKey=8x8_example
      # -Dsonar.verbose=true
      sonarArgs: 

      # Set the sonar.projectBaseDir analysis property
      # Optional, default value: '.' (root directory)
      # Example: "./packages/8x8-example"
      sonarProjectBaseDir: 

      # Build command
      # Example: yarn build-prod
      build:

      # Cypress command
      cypress:

      # Relative path to workspace directory. Root direactory by default. Remove if your project is not a monorepo with multiple packages inside
      # Exmple: packages
      workspaceDirectory:

      # Name of the main branch. Defaults to the repository setup. Delete to use the default value.
      # Example: master
      mainBranch: 

      # Name of the develop branch, used for development purposes.
      # Example: develop
      developBranch:

      # Path to the remote entry file of the MFE. Value relative to the root of the MFE package.
      # Example: dist/index.js
      remoteEntry:

      # Whether to append build metadata to the package released from the main branch version or not.
      # Example: true/false
      hasBuildMetadata:

      # If this is true, publish a SNAPSHOT version if a normal version already exists, instead of showing the VERSION ALREADY EXISTS message (only applicable to publishes from main branch)
      # Example: true/false
      alwaysPublish:

    secrets: inherit
