name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  cd:
    name: cd
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: 8x8/platform-ui-mfe-cd-workflow/.github/workflows/mfe-cd.yml@v1.2
    with:
      ciWorkflowRunId: ${{ github.event.workflow_run.id }}
      namespace: 
      remoteEntry: 
      cdnPublicUrl:
      npmRegistry:
    secrets: inherit


