name: CI

# Workflow trigger setup. For more information: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Runs your workflow when you push a commit or tag.
  push:
    # Running your workflow only when a push to specific branches occurs
    branches:
      - $default-branch
      - releases/**
      - feature/**
  # Runs your workflow when activity on a pull request in the workflow's repository occurs.
  pull_request:
    branches:
      - '*'
  # Trigger workflow manually
  workflow_dispatch:

jobs:
  ci:
    name: ci
    # For more information and detailed docs please check 8x8/platform-ui-mfe-ci-workflow
    # Info: to increase readability of your workflow and support the future default value updates, please delete the keys you're not using
    uses: 8x8/platform-ui-mfe-ci-workflow/.github/workflows/mfe-ci.yml@v1.1
    with:
      # Node version used to run the CI process
      # Default: 18
      nodeVersion:

      # Package manager used in the project
      # Default: npm
      packageManager:

      # NPM registry used to publish artifacts generated by CI (format example: `//artifactory.registry.com/npm/npm-repository/`)
      npmRegistry:
      
      # Install command
      # Default: npn ci
      # Example: yarn install
      install:

      # Test command
      # Example: yarn test
      test: 

      #  Lint command
      # Example: yarn lint
      lint: 

      # Build command
      # Example: yarn build-prod
      build:

      # Relative path to workspace directory. Root direactory by default. Remove if your project is not a monorepo with multiple packages inside
      # Exmple: packages
      workspaceDirectory:

      # Name of the main branch. Defaults to the repository setup. Delete to use the default value.
      # Example: master
      mainBranch: 

      # Name of the develop branch, used for development purposes.
      # Example: develop
      developBranch:

    secrets:
      # NPM registry username for the specified registry.
      # Warning: NEVER expose your secrets in workflows. Instead please use the Encrypted Secrets functionality from Github!
      # Info: For more information please see 8x8/platform-ui-mfe-ci-workflow
      npmUsername:

      # NPM registry password for the specified registry
      npmPassword:

      # NPM registry email address for the username/password combination
      npmEmail: 